version: 2.1

jobs:
  ansible-install:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a4:42:83:01:5d:70:3b:77:55:f0:23:a7:3c:57:8e:39"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook  playbook.yml  -i inventory.txt
            
  
  smoke-test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test commands
          command: |
            URL="http://ec2-44-192-88-239.compute-1.amazonaws.com:3000/"
            if curl -s --head ${URL}
            then
              echo "It worked!"
            else
              echo "It failed"
            fi
workflows:
  my_workflow:
    jobs:
      - ansible-install
      - smoke-test:
          requires:
            - ansible-install