version: 2.1

jobs:
  ansible-install:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f6:20:b2:a0:d4:78:16:a2:e8:1d:da:59:ae:35:65:c3"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook  playbook.yml  -i inventory.txt --private-key ansible-key.pem
           
workflows:
  my_workflow:
    jobs:
      - ansible-install
      