version: 2.1

jobs:
  ansible-install:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0d:45:1d:be:43:23:8c:6b:fa:f0:21:b0:80:47:c0:6e"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook  playbook.yml  -i inventory.txt
workflows:
  my_workflow:
    jobs:
      - ansible-install